-- Supabase Database Setup Script
-- Run this in your Supabase SQL Editor to create the required tables

-- 1. Create chat_messages table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code TEXT NOT NULL,
    sender TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create code_sessions table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.code_sessions (
    room_code TEXT PRIMARY KEY,
    code TEXT,
    language TEXT DEFAULT 'javascript',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create profiles table if it doesn't exist (for user auth)
CREATE TABLE IF NOT EXISTS public.profiles (
    id TEXT PRIMARY KEY,
    email TEXT,
    display_name TEXT,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create rooms table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.rooms (
    room_code TEXT PRIMARY KEY,
    created_by TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create room_participants table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.room_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code TEXT NOT NULL,
    user_name TEXT NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Create users table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY,
    username TEXT,
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Enable Row Level Security (RLS) - Optional, disable if needed for testing
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.code_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 8. Create RLS policies to allow anonymous access (for development)
-- Chat messages policies
DROP POLICY IF EXISTS "Allow anonymous insert on chat_messages" ON public.chat_messages;
CREATE POLICY "Allow anonymous insert on chat_messages" ON public.chat_messages
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous select on chat_messages" ON public.chat_messages;
CREATE POLICY "Allow anonymous select on chat_messages" ON public.chat_messages
    FOR SELECT USING (true);

-- Code sessions policies
DROP POLICY IF EXISTS "Allow anonymous upsert on code_sessions" ON public.code_sessions;
CREATE POLICY "Allow anonymous upsert on code_sessions" ON public.code_sessions
    FOR ALL USING (true);

-- Profiles policies  
DROP POLICY IF EXISTS "Allow anonymous insert on profiles" ON public.profiles;
CREATE POLICY "Allow anonymous insert on profiles" ON public.profiles
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous update on profiles" ON public.profiles;
CREATE POLICY "Allow anonymous update on profiles" ON public.profiles
    FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow anonymous select on profiles" ON public.profiles;
CREATE POLICY "Allow anonymous select on profiles" ON public.profiles
    FOR SELECT USING (true);

-- Rooms policies
DROP POLICY IF EXISTS "Allow anonymous insert on rooms" ON public.rooms;
CREATE POLICY "Allow anonymous insert on rooms" ON public.rooms
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous update on rooms" ON public.rooms;
CREATE POLICY "Allow anonymous update on rooms" ON public.rooms
    FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow anonymous select on rooms" ON public.rooms;
CREATE POLICY "Allow anonymous select on rooms" ON public.rooms
    FOR SELECT USING (true);

-- Room participants policies
DROP POLICY IF EXISTS "Allow anonymous insert on room_participants" ON public.room_participants;
CREATE POLICY "Allow anonymous insert on room_participants" ON public.room_participants
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous select on room_participants" ON public.room_participants;
CREATE POLICY "Allow anonymous select on room_participants" ON public.room_participants
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous delete on room_participants" ON public.room_participants;
CREATE POLICY "Allow anonymous delete on room_participants" ON public.room_participants
    FOR DELETE USING (true);

-- Users policies
DROP POLICY IF EXISTS "Allow anonymous insert on users" ON public.users;
CREATE POLICY "Allow anonymous insert on users" ON public.users
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous update on users" ON public.users;
CREATE POLICY "Allow anonymous update on users" ON public.users
    FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow anonymous select on users" ON public.users;
CREATE POLICY "Allow anonymous select on users" ON public.users
    FOR SELECT USING (true);

-- 9. Enable Realtime for these tables (IMPORTANT!)
-- Go to Database -> Replication in Supabase Dashboard and enable replication for:
-- - chat_messages
-- - code_sessions  
-- - profiles
-- - rooms
-- - room_participants
-- - users

-- 10. Set Replica Identity (needed for realtime) - CRITICAL FOR REAL-TIME UPDATES
ALTER TABLE public.chat_messages REPLICA IDENTITY FULL;
ALTER TABLE public.code_sessions REPLICA IDENTITY FULL;
ALTER TABLE public.profiles REPLICA IDENTITY FULL;
ALTER TABLE public.rooms REPLICA IDENTITY FULL;
ALTER TABLE public.room_participants REPLICA IDENTITY FULL;
ALTER TABLE public.users REPLICA IDENTITY FULL;

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_chat_messages_room_code ON public.chat_messages(room_code);
CREATE INDEX IF NOT EXISTS idx_room_participants_room_code ON public.room_participants(room_code);
CREATE INDEX IF NOT EXISTS idx_rooms_room_code ON public.rooms(room_code);

